### PR TITLE
Change .gitignore to ignore only root level .dory.yml file

### PR DESCRIPTION
**Pull request by EarthlingDavey**

### CODE REVIEW

**Review by wilson1000-MoJ — COMMENTED** [review]
Hey, the actual file is in `deploy/config/local/.dory.yml` 
Dory gets installed on `make` by [the line in this file](https://github.com/ministryofjustice/justice-gov-uk/blob/main/bin/local-dory-check.sh#L21)

**Comment by wilson1000-MoJ** [comment]
Hey Davey, it might be the case that you're looking at another branch. If you merge main with your local you should get the file. 

I've added a screenshot of it below and a [link to the file in this repo](https://github.com/ministryofjustice/justice-gov-uk/blob/main/deploy/config/local/.dory.yml)....

--------

Screenshot 2024-02-08 at 13 19 31

**Comment by wilson1000-MoJ** [comment]
Also, just a thought, it may be hidden on your local machine. It's a .hidden file.

**Comment by EarthlingDavey** [comment]
Oops, it's there. Thanks for explaining!

**Pull request closed without merging**
